### ISSUE TITLE
Deploying from "dags" folder throws unknown error

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/astronomer-cli#3]
![ezgif-3-b5096633fd](https://user-images.githubusercontent.com/8160412/29572908-31822714-8723-11e7-86c2-14a071e95e2a.gif)

**Comment by ryw** [comment]
@cwurtz did you look at this?

**Comment by benjamingregory** [comment]
@ryw This was resolved with switch to Go based CLI.
